### ISSUE TITLE
QL Language

### ISSUE THREAD

**Issue by loopingz** [loopingz/webda.io#202]
**Describe the solution you'd like**
The current Store is lacking a good Query Language. The challenge comes from different implementation between `MongoDB`, `DynamoDB`, `FireStore`, `PostgreSQL`, `FileStore`, `MemoryStore`

**Describe alternatives you've considered**
To allow dynamic switch of services, it need to have a common base, therefore a WebdaQL might be needed: https://gist.github.com/loopingz/60a6ad4a5a5fff612e6da2398f8547b3

**Comment by loopingz** [comment]
See https://github.com/loopingz/webda.io/pull/201

**Comment by loopingz** [comment]
# Tasks

- [ ]  Basic Query
- [ ]  Query simulation
- [ ]  Meta pagination
- [ ]  Permission queryable
- [ ]  GCP multi-indexes management
- [ ]  DynamoDB multi index and optimization
- [ ]  Metrics (query, slowQuery, queryDuration)
- [ ]  Expose query parameter
